name: CD - Deploy

on:
  push:
    branches:
      - main

jobs:
  wait:
    name: Wait for All CI workflows
    uses: ./.github/workflows/wait-for-workflows.yaml
    with:
      workflow_files: |
        ci-backend.yaml
        ci-frontend.yaml
        ci-docker.yaml
        ci-scripts.yaml
        ci-commit.yaml

  deploy:
    name: Deploy
    needs: wait
    if: needs.wait.outputs.all_passed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy website to AWS using docker
        run: echo "All CI Passed. Deploying!"
