name: CD

on:
    workflow_run:
        workflows: [CI]
        types:
            - completed

jobs:
    deploy:
        if: >
            (github.event.workflow_run.conclusion == 'success' ||
             github.event.workflow_run.conclusion == 'skipped') &&
            startsWith(github.event.workflow_run.name, 'CI')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy
              run: echo "Deploying application..."
