name: CI - Backend

on:
  push:
    branches:
      - main
      - "test*"
  pull_request:
    branches:
      - main
      - "test*"

defaults:
  run:
    working-directory: backend
    shell: bash

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Backend Machine
        uses: ./.github/actions/setup-backend-machine

      - name: Run Lint
        run: uv run ruff check

  pytest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Backend Machine
        uses: ./.github/actions/setup-backend-machine

      - name: Run Tests
        run: uv run pytest

  static-check:
    name: Static Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Backend Machine
        uses: ./.github/actions/setup-backend-machine

      - name: Run Static Check
        run: uv run ty check
