name: CI - Docker

on:
  push:
    branches:
      - main
      - "test*"
  pull_request:
    branches:
      - main
      - "test*"

jobs:
  check-development:
    name: Check Development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Development docker image
        run: docker compose -f docker-compose.yaml build
